#!/usr/bin/env bash

itype=${1?"Input installation type! Usage: $0 [root|user]"}
echo "Install for $1:"

hostname=$2
cdir=$(dirname $0)

for k in \
    screenrc \
    gitconfig \
    vimrc
do
    ln -vsf $cdir/.$k ~/.$k
done

ln -vsf $cdir/.tmux.conf ~/.tmux.conf


echo "Add .bashrc link"
echo -e "\n\n\n#Added by my-bash-config\n\n"
cat ~/$cdir/.bashrc >> ~/.bashrc
echo -e "\n\n" >> ~/.bashrc


echo "Set prompt string"
if [ ! -z "$hostname" ]
then
    echo -e "\tReplace host to user hostname: $hostname\n"
    echo `$cdir/prompt.bash $itype`| sed "s/\\\h/$hostname/" >> ~/.bashrc
else
    echo `$cdir/prompt.bash $itype` >> ~/.bashrc
fi


cat $cdir/.zshrc >> ~/.zshrc
$cdir/prompt.zsh $itype


echo -e "\n\n" >> ~/.bashrc
echo -e "\n\n" >> ~/.zshrc


echo "Complete"


#EOF#
