#!/usr/bin/env bash

itype=${1?"Input installation type! Usage: $0 [root|user]"}
echo "Install for $1:"

hostname=$2
cdir=$(dirname $0)

for k in \
    screenrc \
    gitconfig
do
    ln -vsfT $cdir/.$k ~/.$k
done


echo "Add .bashrc link"
echo -e "\n\n\n#Added by my-bash-config\n\n"
cat ~/$cdir/.bashrc >> ~/.bashrc
echo -e "\n\n" >> ~/.bashrc


echo "Set prompt string"
if ! -z $hostname
then
    echo -e "\tReplace host to user hostname: $hostname"
    echo `$cdir/prompt $itype` | sed "s/\\\h/$hostname/" >> ~/.bashrc
else
    echo `$cdir/prompt $itype` >> ~/.bashrc
fi

echo -e "\n\n" >> ~/.bashrc

echo "Load new configuration..."
. ~/.bashrc
echo "Complete"


#EOF#
